### PR TITLE
Update to async-context.cs

### PR DESCRIPTION
**Pull request by jessehylton**
There is no mention of the using statements involved causing confusion for beginning coders as code would appear broken without the using statements.

### CODE REVIEW

**Comment by Still34** [comment]
Hello! Thank you for your contribution. However, I personally do not agree with this proposed change. Regardless of the user's familiarity with the language, upon building the project, they would receive corresponding compiling error regarding the lack of using statement. Furthermore, the use of the snippet is to give the developer a sense of what to implement in their code - not necessarily guiding them into building an application that is geared specifically for the purpose of a Discord bot (e.g. they may want to integrate this in their ASP.NET pipeline). While I can agree that we could put in using statements that are not imported by default (e.g. `System.Threading.Task`), I do not agree with putting in full class names and namespaces for the sake of a simple snippet. 

Thanks!

**Comment by jessehylton** [comment]
Oh okay, My bad there's a site redirecting newbies to this and calling a
proper simple bot tutorial for C#

So I was led to believe it's sole purpose was making a guide for people new
to coding.

I'm so new to coding I don't even know what VS what is showing when I mess
up since coding is just a hobby to me with no prior knowledge.

Even your statement (they may want to integrate this in their ASP.NET
<http://asp.net/> pipeline) makes no sense to me because in so uneducated
in coding beyond basic concepts. lol

But Thank you for explaining it to me. I ended up jumping the gun on that
pull.

**Comment by Still34** [comment]
It's no problem that you opened up a pull request! Don't be discouraged to contribute to open source project just because your first PR received unexpected feedback! 

I understand that you and some readers out there may have trouble understanding the guide due to lack of experience with the language or the .NET ecosystem. However, the target audience of the documentation is mainly focused on those who are interested in using this library with prior knowledge of the language/ecosystem as emphasized in our [introductory page](https://docs.stillu.cc/guides/introduction/intro.html#new-to-netc). 

If we were to explain the basics of some of the aspects of the .NET environment in the articles, we may have to pad out the article's length, which may lead to extra maintenance cost (time) - and unfortunately, this is also very difficult to do since it is hard to mention every problem that a beginner may run into. 

To further reiterate on the goals of the articles: they are here to guide users to use this library, not necessarily guide users on the language *and* the library. 

I hope you understand, and if you have any additional questions, feel free to hit us up in our Discord API channel as mentioned on the intro page. Thanks!

**Comment by Still34** [comment]
Just curious, where were you referred from when you found us?

**Comment by jessehylton** [comment]
It's from here https://www.writebots.com/how-to-make-a-discord-bot/

They explain about the option to use Discord.Net in VS when making a simple
bot application and just kinda throw people off to the site as it's some
kind of tutorial instead of mentioning it's just documents for the code.

(docs.stillu.cc/guides/getting_started/first-bot.html is where I was
directed to)

**Comment by Still34** [comment]
I had seen that article and am aware that some of our readers are coming from that website yes. In fairness to the website, they only recommended our docs as a reference instead of a "beginner-friendly guide." I see where you're coming from, though, since you are directed to our site without context or seeing the introductory page first. Perhaps this is something you can let the author of the website know. My two cents is that by itself, it is not a well-written article for **absolute beginners**, since the developers are not yet familiarized with the language they are about to use.

**Comment by jessehylton** [comment]
Okay. Thank you for the clarification.  :)

**Pull request closed without merging**
